"""empty message

Revision ID: 44a7ee22053c
Revises: ddcd49a1dddc
Create Date: 2026-02-15 08:15:32.795467

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44a7ee22053c"
down_revision: Union[str, Sequence[str], None] = "ddcd49a1dddc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_price_tickers", schema=None) as batch_op:
        batch_op.alter_column("price", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column(
            "open_interest",
            existing_type=sa.FLOAT(),
            type_=sa.Integer(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_price_tickers", schema=None) as batch_op:
        batch_op.alter_column(
            "open_interest",
            existing_type=sa.Integer(),
            type_=sa.FLOAT(),
            existing_nullable=False,
        )
        batch_op.alter_column("price", existing_type=sa.FLOAT(), nullable=False)

    # ### end Alembic commands ###
