"""empty message

Revision ID: eb54d34de603
Revises: 3a6df7d76876
Create Date: 2026-02-13 07:17:28.529601

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb54d34de603"
down_revision: Union[str, Sequence[str], None] = "3a6df7d76876"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_person", schema=None) as batch_op:
        batch_op.create_index("ix_index_app", ["index_app"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_person", schema=None) as batch_op:
        batch_op.drop_index("ix_index_app")

    # ### end Alembic commands ###
