"""empty message

Revision ID: 40a1b45a4aee
Revises: 9af2d7d7cdba
Create Date: 2026-02-12 15:48:36.294868

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40a1b45a4aee"
down_revision: Union[str, Sequence[str], None] = "9af2d7d7cdba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_person", schema=None) as batch_op:
        batch_op.add_column(sa.Column("index_app", sa.Integer(), nullable=False))
        batch_op.create_index("ix_user_email", ["email"], unique=True)
        batch_op.create_unique_constraint("user_email_unique", ["email"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_person", schema=None) as batch_op:
        batch_op.drop_constraint("user_email_unique", type_="unique")
        batch_op.drop_index("ix_user_email")
        batch_op.drop_column("index_app")

    # ### end Alembic commands ###
