"""rename price_ticker to price_ticker_id

Revision ID: a1578f78441e
Revises: 0761f133c127
Create Date: 2026-02-17 09:13:50.333492

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1578f78441e"
down_revision: Union[str, Sequence[str], None] = "0761f133c127"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_person_prices", schema=None) as batch_op:
        batch_op.alter_column("price_ticker", new_column_name="price_ticker_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_person_prices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("price_ticker", sa.INTEGER(), nullable=True))
        batch_op.drop_constraint("fk_person_prices_price_ticker_id", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "crypto_price_tickers", ["price_ticker"], ["id"]
        )
        batch_op.drop_column("price_ticker")

    # ### end Alembic commands ###
