"""empty message

Revision ID: ddcd49a1dddc
Revises: 21695d13ae62
Create Date: 2026-02-14 07:37:39.013959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcd49a1dddc'
down_revision: Union[str, Sequence[str], None] = '21695d13ae62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_person_prices',
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('person', sa.Integer(), nullable=True, comment='Reference to the person database.'),
    sa.Column('price_ticker', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Account index'),
    sa.Column('date_registered', sa.DateTime(), nullable=False, comment='Date and time of registration, it is by server'),
    sa.Column('date_updated', sa.DateTime(), nullable=False, comment='Date and time last updated'),
    sa.ForeignKeyConstraint(['person'], ['crypto_person.id'], ),
    sa.ForeignKeyConstraint(['price_ticker'], ['crypto_price_tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crypto_person_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crypto_person_prices_date_registered'), ['date_registered'], unique=False)
        batch_op.create_index(batch_op.f('ix_crypto_person_prices_date_updated'), ['date_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_crypto_person_prices_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crypto_person_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crypto_person_prices_id'))
        batch_op.drop_index(batch_op.f('ix_crypto_person_prices_date_updated'))
        batch_op.drop_index(batch_op.f('ix_crypto_person_prices_date_registered'))

    op.drop_table('crypto_person_prices')
    # ### end Alembic commands ###
