"""rename price_ticker to price_ticker_id

Revision ID: 7e6984e92e2c
Revises: a1578f78441e
Create Date: 2026-02-17 09:16:34.791039

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e6984e92e2c"
down_revision: Union[str, Sequence[str], None] = "a1578f78441e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
