"""empty message

Revision ID: 9af2d7d7cdba
Revises: 1f7a281e76f9
Create Date: 2026-02-12 15:28:59.585339

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9af2d7d7cdba"
down_revision: Union[str, Sequence[str], None] = "1f7a281e76f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_price_tickers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("instrument_name", sa.String(length=15), nullable=False)
        )
        batch_op.add_column(sa.Column("stats_value", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("stats_low", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("stats_high", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("price_change", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("volume_usd", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("settlement_price", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("delivery_price", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("open_interest", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("best_bid_price", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("best_bid_amount", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("best_ask_price", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("best_ask_amount", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("index_price", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("min_price", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("max_price", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("mark_price", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("last_price", sa.Float(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_crypto_price_tickers_date_registered"))
        batch_op.drop_index(batch_op.f("ix_crypto_price_tickers_ticker"))
        batch_op.drop_index(batch_op.f("ix_crypto_price_tickers_timestamp"))
        batch_op.create_unique_constraint("instrument_name_unique", ["instrument_name"])
        batch_op.create_index("ix_price_tickers_ticker", ["ticker"], unique=False)
        batch_op.drop_column("date_registered")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_price_tickers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("date_registered", sa.DATETIME(), nullable=False))
        batch_op.drop_index("ix_price_tickers_ticker")
        batch_op.drop_constraint("instrument_name_unique", type_="unique")
        batch_op.create_index(
            batch_op.f("ix_crypto_price_tickers_timestamp"), ["timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_crypto_price_tickers_ticker"), ["ticker"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_crypto_price_tickers_date_registered"),
            ["date_registered"],
            unique=False,
        )
        batch_op.drop_column("last_price")
        batch_op.drop_column("mark_price")
        batch_op.drop_column("max_price")
        batch_op.drop_column("min_price")
        batch_op.drop_column("index_price")
        batch_op.drop_column("best_ask_amount")
        batch_op.drop_column("best_ask_price")
        batch_op.drop_column("best_bid_amount")
        batch_op.drop_column("best_bid_price")
        batch_op.drop_column("open_interest")
        batch_op.drop_column("delivery_price")
        batch_op.drop_column("settlement_price")
        batch_op.drop_column("volume_usd")
        batch_op.drop_column("price_change")
        batch_op.drop_column("stats_high")
        batch_op.drop_column("stats_low")
        batch_op.drop_column("stats_value")
        batch_op.drop_column("instrument_name")

    # ### end Alembic commands ###
