"""empty message

Revision ID: 3a6df7d76876
Revises: 40a1b45a4aee
Create Date: 2026-02-12 16:16:56.966809

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a6df7d76876"
down_revision: Union[str, Sequence[str], None] = "40a1b45a4aee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_person", schema=None) as batch_op:
        batch_op.alter_column(
            "index_app",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=50),
            existing_nullable=False,
        )

    with op.batch_alter_table("crypto_price_tickers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "date_registered",
                sa.DateTime(),
                nullable=False,
                comment="Date and time of registration, it is by server",
            )
        )
        batch_op.create_index(
            batch_op.f("ix_crypto_price_tickers_date_registered"),
            ["date_registered"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_price_tickers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crypto_price_tickers_date_registered"))
        batch_op.drop_column("date_registered")

    with op.batch_alter_table("crypto_person", schema=None) as batch_op:
        batch_op.alter_column(
            "index_app",
            existing_type=sa.String(length=50),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
