"""empty message

Revision ID: 21695d13ae62
Revises: e4cbae7b58dd
Create Date: 2026-02-13 18:15:22.968484

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21695d13ae62"
down_revision: Union[str, Sequence[str], None] = "e4cbae7b58dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_person", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("system_name", sa.String(length=50), nullable=False)
        )
        batch_op.add_column(sa.Column("username", sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column("is_password", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_person", schema=None) as batch_op:
        batch_op.drop_column("is_password")
        batch_op.drop_column("username")
        batch_op.drop_column("system_name")

    # ### end Alembic commands ###
