"""rename column and more

Revision ID: 0761f133c127
Revises: 7f386f1a14ea
Create Date: 2026-02-17 08:51:06.027306

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0761f133c127"
down_revision: Union[str, Sequence[str], None] = "7f386f1a14ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_person_prices", schema=None) as batch_op:
        try:
            batch_op.alter_column("person", new_column_name="person_id")

        except:
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_person_prices", schema=None) as batch_op:
        batch_op.alter_column("person", new_column_name="person")

    # ### end Alembic commands ###
