"""empty message

Revision ID: 7f386f1a14ea
Revises: 44a7ee22053c
Create Date: 2026-02-15 15:17:49.998321

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f386f1a14ea"
down_revision: Union[str, Sequence[str], None] = "44a7ee22053c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_price_tickers", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("instrument_name_unique"), type_="unique")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_price_tickers", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("instrument_name_unique"), ["instrument_name"]
        )

    # ### end Alembic commands ###
