"""empty message

Revision ID: 89c1aa86078e
Revises: b404f90b1ac0
Create Date: 2026-02-12 13:14:35.422394

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89c1aa86078e"
down_revision: Union[str, Sequence[str], None] = "b404f90b1ac0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypto_person",
        sa.Column("person_role", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("client_id", sa.String(), nullable=False),
        sa.Column("client_secret", sa.String(), nullable=False),
        sa.Column("is_access", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Account index",
        ),
        sa.Column(
            "date_registered",
            sa.DateTime(),
            nullable=False,
            comment="Date and time of registration, it is by server",
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(),
            nullable=False,
            comment="Date and time last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("crypto_person", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_crypto_person_date_registered"),
            ["date_registered"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_crypto_person_date_updated"), ["date_updated"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_crypto_person_id"), ["id"], unique=False)

    op.create_table(
        "crypto_price_tickers",
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.Integer(), nullable=False),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Account index",
        ),
        sa.Column(
            "date_registered",
            sa.DateTime(),
            nullable=False,
            comment="Date and time of registration, it is by server",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("crypto_price_tickers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_crypto_price_tickers_date_registered"),
            ["date_registered"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_crypto_price_tickers_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_crypto_price_tickers_ticker"), ["ticker"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_crypto_price_tickers_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crypto_price_tickers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crypto_price_tickers_timestamp"))
        batch_op.drop_index(batch_op.f("ix_crypto_price_tickers_ticker"))
        batch_op.drop_index(batch_op.f("ix_crypto_price_tickers_id"))
        batch_op.drop_index(batch_op.f("ix_crypto_price_tickers_date_registered"))

    op.drop_table("crypto_price_tickers")
    with op.batch_alter_table("crypto_person", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crypto_person_id"))
        batch_op.drop_index(batch_op.f("ix_crypto_person_date_updated"))
        batch_op.drop_index(batch_op.f("ix_crypto_person_date_registered"))

    op.drop_table("crypto_person")
    # ### end Alembic commands ###
